USE [master]
GO
/****** Object:  Database [Ñuflo]    Script Date: 15/10/2015 08:12:44 p.m. ******/
CREATE DATABASE [Ñuflo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ñuflo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER2012\MSSQL\DATA\Ñuflo.mdf' , SIZE = 17408KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Ñuflo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLSERVER2012\MSSQL\DATA\Ñuflo_log.ldf' , SIZE = 92864KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Ñuflo] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ñuflo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ñuflo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ñuflo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ñuflo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ñuflo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ñuflo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ñuflo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ñuflo] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Ñuflo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ñuflo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ñuflo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ñuflo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ñuflo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ñuflo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ñuflo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ñuflo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ñuflo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ñuflo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ñuflo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ñuflo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ñuflo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ñuflo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ñuflo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ñuflo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ñuflo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Ñuflo] SET  MULTI_USER 
GO
ALTER DATABASE [Ñuflo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ñuflo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ñuflo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ñuflo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

USE [Ñuflo]
GO
/****** Object:  Schema [gd_ñuflo]    Script Date: 15/10/2015 08:12:44 p.m. ******/
CREATE SCHEMA [gd_ñuflo]
GO

USE [master]
GO
ALTER DATABASE [Ñuflo] SET  READ_WRITE 
GO